### ISSUE TITLE
#TK Crear y mantener actualizado el archivo README con información relevante del proyecto.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#1]
Se requiere participación de todos los contributores.

**Comment by NoeCoast** [comment]
Se requiere participación de todos los contributores.

**Comment by NoeCoast** [comment]
@KaterinnePeralta @danielpozzo @DiegolPl @NoeCoast @NoeVelaz @ChristMorales @anibal-morales @todotirreno

**Comment by danielpozzo** [comment]
Generé el archivo al momento de crear el repositorio del presente proyecto, desarrollando su estructura general, introducción y algunos enlaces de interés para el equipo de desarrollo y profesores a la hora de evaluar el mismo..

**Comment by danielpozzo** [comment]
He completado los contenidos del archivo. Queda en condiciones de cerrarse esta instancia.
