### ISSUE TITLE
#TK Crear ramas de trabajo según la metodología establecida.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#11]
Se requiere participación de todos los contributores.

**Comment by danielpozzo** [comment]
Hola equipo les informo que he creado mi rama personal Dev-Daniel-Pozzo y las organizacionales feature y develop cumpliendo con la estructuras de ramas que venimos adoptando en nuestros proyectos.

**Comment by NoeCoast** [comment]
@KaterinnePeralta @danielpozzo @DiegolPl @NoeCoast @NoeVelaz @ChristMorales @anibal-morales @todotirreno 

- [x] Aníbal Morales
- [x] Carlos Daniel Pozzo
- [x] Christopher Morales
- [x] Diego Ponce de Leon
- [x] Julián Donamaria
- [x] Katerinne Peralta
- [x] Noe Velázquez
- [x] Noe Zalazar

**Comment by DiegolPl** [comment]
He creado mi rama personal de desarrollo!

**Comment by NoeCoast** [comment]
He creado mi rama personal de desarrollo. Y compartí la información de la misma en el apartado de presentación de equipo.

**Comment by danielpozzo** [comment]
Corroboré que todas las ramas han sido creadas por lo que procedo a cerrar esta instancia.
