### ISSUE TITLE
#TK Refuncionalizar la Aplicación Web.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#12]
Cuando decimos refuncionalizar nos referimos a realizar todas las acciones necesarias, tanto de investigación como de aplicación, que pongan operativa (online) a nuestra aplicación web.

**Comment by DiegolPl** [comment]
Se estuvo realizando un análisis del estado actual de la web junto a @danielpozzo  y un ex integrante del proyecto, llegando a la conclusión de que había problemas con el servidor donde se encontraba hosteado el proyecto web y que nuestro dominio había caducado. Por lo cual decidimos investigar alternativas, en caso de no poder solucionar el problema del hosting que veníamos utilizando, y adquirir un nuevo dominio.

**Comment by danielpozzo** [comment]
En sintonía con lo expresado por Diego, concretamos la adquisición de un nuevo dominio, cambié la configuración de los DNS's redirigiéndolos a los servidores que nos brindan el servicio de hosting.
A la fecha nuestro dominio se encuentra online en servidores de EEUU, Canadá, Brasil, España, Francia, Alemania, Suiza, Italia, Sudáfrica, Turquía, Pakistán, India, Malasia, Singapur, Korea del Sur, Japón y Australia.
Para la verificación utilizamos la herramienta https://www.whatsmydns.net/
