### ISSUE TITLE
#TK Crear un apartado en la wiki para presentar a los integrantes del equipo.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#16]
https://github.com/Dev-Full-Solutions/AnalizAr/wiki/Dev‐Full‐Solutions---AnalizAr-Development-Team

**Comment by danielpozzo** [comment]
He completado mi presentación y la de la profesora Viviana Guillén como PO del proyecto.

**Comment by NoeCoast** [comment]
@KaterinnePeralta @danielpozzo @DiegolPl @NoeCoast @NoeVelaz @ChristMorales @anibal-morales @todotirreno 

- [x] Aníbal Morales
- [x] Carlos Daniel Pozzo
- [x] Christopher Morales
- [x] Diego Ponce de Leon
- [x] Julián Donamaria
- [x] Katerinne Peralta
- [ ] Noe Velázquez
- [x] Noe Zalazar

**Comment by DiegolPl** [comment]
He completado mi presentación como Desarrollador
