### ISSUE TITLE
#TK Establecer un repositorio en Drive para almacenar la documentación del proyecto y mantenerlo actualizado.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#20]
Se requiere participación de todos los contributores.

**Comment by NoeCoast** [comment]
@KaterinnePeralta @danielpozzo @DiegolPl @NoeCoast @NoeVelaz @ChristMorales @anibal-morales @todotirreno

**Comment by danielpozzo** [comment]
Creé la carpeta (repositorio) en mi Drive de Google https://drive.google.com/drive/folders/1CIp1PRNUf7VTK9WXjWleznPwEPEAIURV?usp=drive_link para almacenar los recursos del proyecto AnalizAr.

**Comment by danielpozzo** [comment]
Generé el documento de Drive https://docs.google.com/document/d/1UFA0uuWflkYRx6pbTk7taQT19Bx_8SBng-ZbFoSzKEE/edit?usp=drive_link para documentar enlaces de materiales para abordar el desarrollo de accesibilidad Web y Móvil en nuestro proyecto.
Añadí los primeros 4 enlaces para abordar a partir del inicio del Sprint1.
