### ISSUE TITLE
#TK Reorganizar la documentación mediante una nueva estructura de repositorios.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#23]

**Comment by NoeCoast** [comment]
@danielpozzo

**Comment by danielpozzo** [comment]
Definimos una estructura de **3 repositorios** dentro de la organización **Dev-Full-Solutions**. Los mismos son:

1. AnalizAr - Repositorio para la gestión integral de la documentación del proyecto a lo largo de sus 3 etapas/fases de desarrollo (Sprints).
2. AnalizArWeb - Repositorio forkeado con el código desarrollado durante el proyecto ISPCFullStackProjetc del módulo Programado Web y donde realizaremos las mejoras propuestas en el Trabajo Final del Espacio Curricular "Práctica Profesionalizante".
3. AnalizArApp - Repositorio con el código desarrollado durante el proyecto homónimo correspondiente al módulo "Programador de Aplicaciones Móviles donde realizaremos las mejoras propuestas en  el Trabajo Final del Espacio Curricular "Práctica Profesionalizante".
