### ISSUE TITLE
#TK Realizar el fork del repositorio ISPCFullStackProject que contiene el código de la SPA.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizAr#26]

**Comment by NoeCoast** [comment]
@danielpozzo

**Comment by danielpozzo** [comment]
Realicé el fork del repositorio original ISPCFullStackProject como AnalizArWeb dentro de la organización Dev-Full-Solutions...
Ya se encuentra disponible para ser clonado a los repositorios locales de los integrantes del equipo de desarrollo.
