### ISSUE TITLE
#TK Adquirir un nuevo dominio para la SPA y asegurar su funcionalidad.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizAr#32]

**Comment by NoeCoast** [comment]
@danielpozzo  @anibal-morales

**Comment by danielpozzo** [comment]
Realicé las averiguaciones necesarias para adquirir un dominio que cumpla con los requerimientos para poder ser utilizado en nuestro proyecto logrando que la aplicación web esté online.
Conseguí la opción analizar.xyz de Hostinger.
Aníbal Morales concretó la compra.

**Comment by danielpozzo** [comment]
Actualmente el dominio adquirido se encuentra redireccionado al servicio de Hosting que conseguimos sin costo y replicado en varios DNS's para una mejor velocidad de carga en cualquier parte del mundo.

![Image](https://github.com/Dev-Full-Solutions/AnalizAr/assets/106629005/dab52aa4-1121-43b2-b93b-b124bb85f717)
