### ISSUE TITLE
#US01 Como usuario propietario de la Web, quiero que los usuarios puedan descargar la aplicación móvil desde la SPA, para facilitarles el uso de ambas plataformas.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#35]

**Comment by danielpozzo** [comment]
Añadí un botón de descarga del archivo APK respetando los estilos institucionales de la marca AnalizAr.
El mismo abre el enlace de descarga en una nueva ventana para que el usuario pueda retomar la navegación de la SPA con solo cerrar dicha ventana una vez finalizada la descarga.

![Image](https://github.com/Dev-Full-Solutions/AnalizAr/assets/106629005/a3bc5f85-a677-46f5-bed4-67c13bc90c9d)

Añadí una nota dirigida al usuario como guía para completar el proceso sin inconvenientes.
