### ISSUE TITLE
#TK Evaluar la accesibilidad de la SPA para mejorar la experiencia del usuario y garantizar un acceso igualitario para todas las personas.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizAr#4]

**Comment by NoeCoast** [comment]
Evaluar la accesibilidad para mejorar la experiencia del usuario y garantizar un acceso igualitario para todas las personas.

**Comment by NoeCoast** [comment]
Se sugiere la participación de todos los contributores.
@KaterinnePeralta @DiegolPl @ChristMorales @NoeCoast  @NoeVelaz @danielpozzo @todotirreno  @anibal-morales
