### ISSUE TITLE
#TK Crear ramas de trabajo en el repositorio AnalizArWeb

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#45]
- Repo: https://github.com/Dev-Full-Solutions/AnalizArWeb.git

- Nomenclatura de branches: DevNombreApellido

@KaterinnePeralta @danielpozzo @DiegolPl @NoeCoast @NoeVelaz @ChristMorales @anibal-morales @todotirreno

**Comment by danielpozzo** [comment]
En mi caso no es necesario crear la rama, ya que, seguiré utilizando la que utilicé en el proyecto ISPCFullStackProject y que cumple con nomenclatura definida por el equipo **Dev+Nombre+Apellido => DevDanielPozzo**.

**Comment by danielpozzo** [comment]
- [x] @KaterinnePeralta 
- [x] @NoeCoast 
- [ ] @NoeVelaz 
- [x] @anibal-morales 
- [x] @ChristMorales 
- [x] @DiegolPl 
- [x] @danielpozzo 
- [x] @todotirreno
