### ISSUE TITLE
#TK Elaborar la presentación del proyecto y publicarla en la Wiki.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#7]
Se requiere participación de todos los contributores.

(Enlace de acceso: https://github.com/Dev-Full-Solutions/AnalizAr/wiki)

**Comment by NoeCoast** [comment]
@KaterinnePeralta @danielpozzo @DiegolPl @NoeCoast @NoeVelaz @ChristMorales @anibal-morales @todotirreno

**Comment by danielpozzo** [comment]
He completado el presente requerimiento.
