### ISSUE TITLE
#US02 Como usuarios quiero poder editar, agregar y eliminar las configuraciones de iluminación existentes, para adaptarlas a mis preferencias específicas y mejorar la eficiencia de mi hogar.

### ISSUE THREAD

**Issue by KaterinnePeralta** [Dev-Full-Solutions/AnalizAr#70]
- [ ] Diseñar e implementar una interfaz de usuario para la edición de detalles de alarmas de iluminación, que incluya opciones como hora de activación, tono de notificación, etc.
- [ ] Desarrollar la lógica para permitir a los usuarios modificar y guardar los detalles de las alarmas de iluminación según sus preferencias. 
- [ ] Integrar la funcionalidad de edición de alarmas con el sistema de gestión de notificaciones de la aplicación.
- [ ] Realizar pruebas de extremo a extremo para asegurar que los cambios realizados en los detalles de las alarmas se reflejen correctamente en el sistema de notificaciones. 

**Criterios de aceptación**

- [ ] Los usuarios pueden acceder a la funcionalidad de edición de detalles de alarmas de iluminación de manera intuitiva desde la aplicación.
- [ ] Los cambios realizados en los detalles de las alarmas se reflejan correctamente en el sistema de notificaciones de la aplicación.
- [ ] Las alarmas modificadas se activan y desactivan según las preferencias del usuario.

**Comment by ChristMorales** [comment]
CRUD created
