### ISSUE TITLE
#US06 Como administrador, quiero añadir funcionalidades de accesibilidad, para que más personas puedan acceder a los beneficios de nuestra aplicación móvil. 

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#74]
@danielpozzo 

- [x] Implementar la compatibilidad con lectores de pantalla en todas las activities de la aplicación.

- [x] Corroborar que todos los textos utilicen la unidad de medida “sp” y los demás elementos “dp” para permitir que los textos puedan ser redimensionados según las preferencias de los usuarios.

- [x] Habilitar la navegación por teclado para usuarios que utilizan teclados físicos o virtuales.

**Criterios de Aceptación:** 

- [x] Los usuarios con visión reducida o con visión nula o escasa podrán navegar la aplicación móvil gracias a los lectores de pantalla de sus dispositivos.

- [x] Los usuarios de nuestra aplicación dispondrán de la funcionalidad de adecuar el tamaño de los textos en sus dispositivos según sus necesidades.

- [x] Los usuarios experimentarán una mejor experiencia de usuario al poder navegar nuestra aplicación móvil de diferente maneras (soportes tecnológicos).

**Comment by danielpozzo** [comment]
NOTA: Activity Contacto cumple todos los criterios... Las demás necesitan ajustes que no pude abordar por estar en desarrollo y agotarse el tiempo para ello.
