### ISSUE TITLE
#TK Desarrollar el apartado dedicado a las ceremonias en la plataforma Wiki y mantenerlo actualizado.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#8]
https://github.com/Dev-Full-Solutions/AnalizAr/wiki/Ceremonias

@KaterinnePeralta @danielpozzo

**Comment by danielpozzo** [comment]
Ya realicé el apartado para las ceremocias Planning y Retrospective del proyecto... Me falta realizar el de las Daily's.

**Comment by danielpozzo** [comment]
Completé el requerimiento añadiendo las ceremonias Daily's y Review's en el apartado ceremonias de la Wiki.
Completé el apartado para que contenga la misma estructura para los Sprints 1 y 2.
