### ISSUE TITLE
#TK Desarrollar el apartado (bitácora) dedicado a las contribuciones de los integrantes del equipo de desarrollo en la plataforma Wiki.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#9]
https://github.com/Dev-Full-Solutions/AnalizAr/wiki/Bitácora-‐-Registro-de-Actividades-del-Equipo-de-Desarrollo

**Comment by DiegolPl** [comment]
Agregada mi actividad durante el sprint 0

**Comment by danielpozzo** [comment]
Actualicé la bitácora con mis particiaciones durante las semanas1 y 2 del Sprint0.
